# Generated by Django 2.2.2 on 2019-07-11 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(max_length=50)),
                ('bulletinUrl', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ptptype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptptype', models.CharField(max_length=20)),
                ('sysname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ptp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('carRedSignal', models.BooleanField()),
                ('carTurnLeft', models.BooleanField()),
                ('carTurnRight', models.BooleanField()),
                ('pedRedSignal', models.BooleanField()),
                ('pedWrongCross', models.BooleanField()),
                ('pedKid', models.BooleanField()),
                ('danger', models.BooleanField()),
                ('city', models.ForeignKey(db_column='id_city', on_delete=django.db.models.deletion.PROTECT, to='mapedit.city')),
                ('ptptype', models.ForeignKey(db_column='id_ptptype', on_delete=django.db.models.deletion.PROTECT, to='mapedit.ptptype')),
            ],
        ),
    ]
