# Generated by Django 2.2.2 on 2019-07-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapedit', '0002_auto_20190711_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptp',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
