# Generated by Django 2.2.2 on 2019-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapedit', '0004_usercity'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='sysname',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
